name: "Terraform-apply"

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:   

jobs:
  # terraform-module:
  #   name: "Terraform-module"
  #   runs-on: ubuntu-latest
  #   env:	
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
  #     AWS_REGION: 'ap-east-1'

  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@master
  #     - name: 'Terraform Init'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: 1.0.11
  #         tf_actions_subcommand: 'init'
  #         tf_actions_working_dir: './modules/vpc'
  #         tf_actions_comment: true
  #     - name: 'Terraform plan'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: 1.0.11
  #         tf_actions_subcommand: 'plan'
  #         tf_actions_working_dir: './modules/vpc'
  #         tf_actions_comment: true  
  #     - name: 'Terraform apply'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: 1.0.11
  #         tf_actions_subcommand: 'apply'
  #         tf_actions_working_dir: './modules/vpc'
  #         tf_actions_comment: true                      
  terraform-sandbox:
    name: "sandbox-Terraform-plan"

    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: 'us-east-1'
      TERRAFORM_ENVIRONMENT: sandbox
      TERRAFORM_VERSION: 0.12.13

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true          
      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true                     
  terraform-sandbox-apply:
    
    name: "sandbox-Terraform-appy"
    needs: terraform-sandbox
 

    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: 'us-east-1'
      TERRAFORM_ENVIRONMENT: sandbox

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true            
                
      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true           
          
