name: "Terraform-apply"

on:
  pull_request:
    types: [ closed ]

jobs:
  # terraform-module:
  #   name: "Terraform-module"
  #   runs-on: ubuntu-latest
  #   env:	
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
  #     AWS_REGION: 'ap-east-1'

  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@master
  #     - name: 'Terraform Init'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: 1.0.11
  #         tf_actions_subcommand: 'init'
  #         tf_actions_working_dir: './modules/vpc'
  #         tf_actions_comment: true
  #     - name: 'Terraform plan'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: 1.0.11
  #         tf_actions_subcommand: 'plan'
  #         tf_actions_working_dir: './modules/vpc'
  #         tf_actions_comment: true  
  #     - name: 'Terraform apply'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: 1.0.11
  #         tf_actions_subcommand: 'apply'
  #         tf_actions_working_dir: './modules/vpc'
  #         tf_actions_comment: true           
  terraform:
    name: "Terraform"
    needs: terraform-sandbox    
    environment:
      name: production
      url: ${{ steps.deploy_production.outputs.webapp-url }}    
    
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: 'us-east-2'
      TERRAFORM_ENVIRONMENT: production

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true
   

      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master

        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true                          
      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true            
                 
  terraform-sandbox:
    name: "sandbox-Terraform"
    environment:
      name: sandbox
      url: ${{ steps.deploy_sandbox.outputs.webapp-url }}    

    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: 'us-east-1'
      TERRAFORM_ENVIRONMENT: sandbox

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true          
      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true    
                
      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './environments/$TERRAFORM_ENVIRONMENT'
          tf_actions_comment: true           
          
